server:
  port: 8080

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false  # we defined explicit routed below for clarity
      routes:
        - id: auth-service
          uri: lb://auth-service  # lb:// => client side load balancer via eureka
          predicates:
            - Path=/auth/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/products/**
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/orders/**
        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path=/inventory/**
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/notifications/**
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/payments/**
        - id: cart-service
          uri: lb://cart-service
          predicates:
            - Path=/carts/**

# Paths that don't require on JWT (handled by the gateway's JwtAuthenticationFilter)
gateway:
  security:
    open-endpoints:
      - /auth       # Register, Login, Refresh, Logout are all public
      - /eureka