server:
  port: 8081

spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;instanceName=SQLEXPRESS;databaseName=ecommerce_auth;encrypt=true;trustServerCertificate=true
    username: ecommerce-spring-user
    password: Ecommerce@Big4#Pass2026
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.SQLServerDialect

  application:
    name: auth-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

jwt:
  secret: myVeryLongSecretKeyForJwtAuthenticationAndAuthorization123456
  expiration: 3600000
  refresh-expiration: 604800000

management:
  endpoints:
    web:
      exposure:
        include: "*"